const frenchWords = [
  { french: "ailleurs", english: "Elsewhere", options: ["Nearby", "Elsewhere", "Inside", "Everywhere"] },
  { french: "pourtant", english: "Yet", options: ["Therefore", "Already", "Yet", "Almost"] },
  { french: "davantage", english: "More", options: ["More", "Less", "Enough", "Too much"] },
  { french: "désormais", english: "From now on", options: ["Previously", "Occasionally", "Immediately", "From now on"] },
  { french: "autrefois", english: "Formerly", options: ["Recently", "Formerly", "Currently", "Eventually"] },
  { french: "bientôt", english: "Soon", options: ["Yesterday", "Always", "Soon", "Never"] },
  { french: "surtout", english: "Especially", options: ["Especially", "Rarely", "Perhaps", "Together"] },
  { french: "malgré", english: "Despite", options: ["During", "Without", "Before", "Despite"] },
  { french: "parmi", english: "Among", options: ["Behind", "Among", "Against", "Above"] },
  { french: "environ", english: "Approximately", options: ["Exactly", "Completely", "Approximately", "Frequently"] },
  { french: "souvent", english: "Often", options: ["Often", "Soon", "Late", "Still"] },
  { french: "rarement", english: "Rarely", options: ["Usually", "Always", "Quickly", "Rarely"] },
  { french: "presque", english: "Almost", options: ["Only", "Almost", "Also", "Again"] },
  { french: "plutôt", english: "Rather", options: ["Later", "Outside", "Rather", "Yesterday"] },
  { french: "ensemble", english: "Together", options: ["Together", "Alone", "Apart", "Nearby"] },
  { french: "cependant", english: "However", options: ["Because", "Whenever", "Moreover", "However"] },
  { french: "puisque", english: "Since", options: ["Unless", "Since", "Although", "Before"] },
  { french: "lorsque", english: "When", options: ["Where", "Why", "When", "How"] },
  { french: "sinon", english: "Otherwise", options: ["Otherwise", "Therefore", "Indeed", "Meanwhile"] },
  { french: "néanmoins", english: "Nevertheless", options: ["Consequently", "Similarly", "Finally", "Nevertheless"] },
  { french: "réussir", english: "To succeed", options: ["To fail", "To succeed", "To hesitate", "To refuse"] },
  { french: "échouer", english: "To fail", options: ["To improve", "To agree", "To fail", "To arrive"] },
  { french: "choisir", english: "To choose", options: ["To choose", "To borrow", "To forget", "To repair"] },
  { french: "prévoir", english: "To foresee", options: ["To remember", "To discover", "To explain", "To foresee"] },
  { french: "éviter", english: "To avoid", options: ["To invite", "To avoid", "To repeat", "To follow"] },
  { french: "atteindre", english: "To reach", options: ["To wait", "To leave", "To reach", "To lose"] },
  { french: "améliorer", english: "To improve", options: ["To improve", "To damage", "To hide", "To compare"] },
  { french: "empêcher", english: "To prevent", options: ["To allow", "To suggest", "To promise", "To prevent"] },
  { french: "permettre", english: "To allow", options: ["To forbid", "To allow", "To protect", "To require"] },
  { french: "obtenir", english: "To obtain", options: ["To offer", "To return", "To obtain", "To spend"] },
  { french: "recevoir", english: "To receive", options: ["To receive", "To send", "To sell", "To lend"] },
  { french: "apercevoir", english: "To catch sight of", options: ["To listen to", "To look after", "To get rid of", "To catch sight of"] },
  { french: "remarquer", english: "To notice", options: ["To ignore", "To notice", "To guess", "To warn"] },
  { french: "partager", english: "To share", options: ["To keep", "To gather", "To share", "To replace"] },
  { french: "emprunter", english: "To borrow", options: ["To borrow", "To lend", "To buy", "To earn"] },
  { french: "prêter", english: "To lend", options: ["To rent", "To owe", "To save", "To lend"] },
  { french: "dépenser", english: "To spend", options: ["To earn", "To spend", "To borrow", "To count"] },
  { french: "économiser", english: "To save money", options: ["To lose money", "To exchange money", "To save money", "To lend money"] },
  { french: "déménager", english: "To move house", options: ["To move house", "To clean", "To travel", "To decorate"] },
  { french: "ranger", english: "To tidy up", options: ["To wake up", "To break down", "To give up", "To tidy up"] },
  { french: "réparer", english: "To repair", options: ["To build", "To repair", "To destroy", "To paint"] },
  { french: "remplacer", english: "To replace", options: ["To remove", "To collect", "To replace", "To organize"] },
  { french: "ajouter", english: "To add", options: ["To add", "To divide", "To reduce", "To erase"] },
  { french: "enlever", english: "To remove", options: ["To attach", "To fill", "To cover", "To remove"] },
  { french: "réduire", english: "To reduce", options: ["To increase", "To reduce", "To maintain", "To measure"] },
  { french: "augmenter", english: "To increase", options: ["To decrease", "To disappear", "To increase", "To continue"] },
  { french: "soutenir", english: "To support", options: ["To support", "To oppose", "To abandon", "To interrupt"] },
  { french: "proposer", english: "To suggest", options: ["To demand", "To deny", "To regret", "To suggest"] },
  { french: "refuser", english: "To refuse", options: ["To accept", "To refuse", "To explain", "To forgive"] },
  { french: "avouer", english: "To admit", options: ["To conceal", "To accuse", "To admit", "To complain"] },
  { french: "craindre", english: "To fear", options: ["To fear", "To hope", "To enjoy", "To trust"] },
  { french: "espérer", english: "To hope", options: ["To doubt", "To worry", "To regret", "To hope"] },
  { french: "souhaiter", english: "To wish", options: ["To decide", "To wish", "To remember", "To attempt"] },
  { french: "mériter", english: "To deserve", options: ["To depend", "To belong", "To deserve", "To appear"] },
  { french: "appartenir", english: "To belong", options: ["To belong", "To become", "To disappear", "To return"] },
  { french: "dépendre", english: "To depend", options: ["To decide", "To explain", "To prepare", "To depend"] },
  { french: "manquer", english: "To lack", options: ["To possess", "To lack", "To discover", "To achieve"] },
  { french: "oser", english: "To dare", options: ["To obey", "To hesitate", "To dare", "To rest"] },
  { french: "réfléchir", english: "To think carefully", options: ["To think carefully", "To speak loudly", "To act quickly", "To sleep deeply"] },
  { french: "se souvenir", english: "To remember", options: ["To introduce oneself", "To hurry", "To get dressed", "To remember"] },
  { french: "le besoin", english: "Need", options: ["Choice", "Need", "Habit", "Advice"] },
  { french: "le conseil", english: "Advice", options: ["Mistake", "Promise", "Advice", "Danger"] },
  { french: "le choix", english: "Choice", options: ["Choice", "Reason", "Result", "Effort"] },
  { french: "la raison", english: "Reason", options: ["Season", "Feeling", "Request", "Reason"] },
  { french: "le résultat", english: "Result", options: ["Beginning", "Result", "Goal", "Method"] },
  { french: "le progrès", english: "Progress", options: ["Delay", "Failure", "Progress", "Trouble"] },
  { french: "l'effort", english: "Effort", options: ["Effort", "Reward", "Rest", "Luck"] },
  { french: "l'habitude", english: "Habit", options: ["Skill", "Memory", "Opinion", "Habit"] },
  { french: "l'avis", english: "Opinion", options: ["Permission", "Opinion", "Appointment", "Evidence"] },
  { french: "la confiance", english: "Trust", options: ["Doubt", "Shame", "Trust", "Anger"] },
  { french: "le doute", english: "Doubt", options: ["Doubt", "Pride", "Joy", "Courage"] },
  { french: "la crainte", english: "Fear", options: ["Hope", "Relief", "Surprise", "Fear"] },
  { french: "le bonheur", english: "Happiness", options: ["Sadness", "Happiness", "Boredom", "Pain"] },
  { french: "la colère", english: "Anger", options: ["Kindness", "Patience", "Anger", "Curiosity"] },
  { french: "la honte", english: "Shame", options: ["Shame", "Confidence", "Excitement", "Peace"] },
  { french: "la fierté", english: "Pride", options: ["Fear", "Envy", "Regret", "Pride"] },
  { french: "le souci", english: "Worry", options: ["Pleasure", "Worry", "Success", "Desire"] },
  { french: "l'enjeu", english: "What is at stake", options: ["What is missing", "What is forbidden", "What is at stake", "What is finished"] },
  { french: "le délai", english: "Time limit", options: ["Time limit", "Discount", "Distance", "Schedule"] },
  { french: "la démarche", english: "Procedure", options: ["Destination", "Mistake", "Achievement", "Procedure"] },
  { french: "le quartier", english: "Neighborhood", options: ["Building", "Neighborhood", "Countryside", "Border"] },
  { french: "le logement", english: "Housing", options: ["Furniture", "Transport", "Housing", "Clothing"] },
  { french: "le loyer", english: "Rent", options: ["Rent", "Salary", "Tax", "Loan"] },
  { french: "le salaire", english: "Salary", options: ["Savings", "Debt", "Price", "Salary"] },
  { french: "l'embauche", english: "Hiring", options: ["Retirement", "Hiring", "Training", "Resignation"] },
  { french: "la réunion", english: "Meeting", options: ["Journey", "Break", "Meeting", "Competition"] },
  { french: "le renseignement", english: "Information", options: ["Information", "Equipment", "Payment", "Permission"] },
  { french: "la preuve", english: "Proof", options: ["Rumor", "Question", "Warning", "Proof"] },
  { french: "le dommage", english: "Damage", options: ["Benefit", "Damage", "Repair", "Expense"] },
  { french: "le comportement", english: "Behavior", options: ["Appearance", "Knowledge", "Behavior", "Background"] },
  { french: "fiable", english: "Reliable", options: ["Reliable", "Fragile", "Careless", "Temporary"] },
  { french: "disponible", english: "Available", options: ["Busy", "Expensive", "Necessary", "Available"] },
  { french: "utile", english: "Useful", options: ["Useless", "Useful", "Difficult", "Ordinary"] },
  { french: "inutile", english: "Useless", options: ["Essential", "Practical", "Useless", "Convenient"] },
  { french: "précis", english: "Precise", options: ["Precise", "Vague", "Simple", "Strange"] },
  { french: "semblable", english: "Similar", options: ["Different", "Separate", "Opposite", "Similar"] },
  { french: "étrange", english: "Strange", options: ["Familiar", "Strange", "Obvious", "Regular"] },
  { french: "inquiet", english: "Worried", options: ["Calm", "Pleased", "Worried", "Proud"] },
  { french: "déçu", english: "Disappointed", options: ["Disappointed", "Delighted", "Confused", "Exhausted"] },
  { french: "soulagé", english: "Relieved", options: ["Embarrassed", "Annoyed", "Surprised", "Relieved"] }
];